### PR TITLE
Note about execution directory to pick up static build files

### PR DESCRIPTION
**Pull request by iloveitaly**

### CODE REVIEW

**Comment by ErikBjare** [comment]
This seems like unwanted behavior. Should probably be fixed rather than documented.

**Comment by johan-bjareholt** [comment]
It already looks at the path for the executable.

https://github.com/ActivityWatch/aw-server-rust/blob/8bf4cb3/aw-server/src/main.rs#L206

**Comment by iloveitaly** [comment]
the problem is `venv/bin/aw-server-rust` is *not* the directory that
contains the static build files. That's `aw-server-rust/aw-webui/dist`.

**Comment by iloveitaly** [comment]
@johan-bjareholt any additional thoughts here?

**Comment by ErikBjare** [comment]
Sorry for not getting back on this.

Static assets are now bundled into the binary at build-time, so this PR is outdated.

Closing. Thanks for the effort @iloveitaly!

**Pull request closed without merging**
